/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DianProtocol"
 * 	found in "dian.asn"
 * 	`asn1c -pdu=auto`
 */

#include "DianConnectionResp.h"

static asn_TYPE_member_t asn_MBR_DianConnectionResp_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DianConnectionResp, userIdentity),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_User_Identity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"userIdentity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DianConnectionResp, respType),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Response_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"respType"
		},
	{ ATF_POINTER, 2, offsetof(struct DianConnectionResp, denyReason),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Deny_Reason,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"denyReason"
		},
	{ ATF_POINTER, 1, offsetof(struct DianConnectionResp, helloMsg),
		(ASN_TAG_CLASS_UNIVERSAL | (19 << 2)),
		0,
		&asn_DEF_Message,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"helloMsg"
		},
};
static const int asn_MAP_DianConnectionResp_oms_1[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_DianConnectionResp_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DianConnectionResp_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* userIdentity */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 1, 0, 1 }, /* respType */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 2, -1, 0 }, /* denyReason */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 3, 0, 0 } /* helloMsg */
};
static asn_SEQUENCE_specifics_t asn_SPC_DianConnectionResp_specs_1 = {
	sizeof(struct DianConnectionResp),
	offsetof(struct DianConnectionResp, _asn_ctx),
	asn_MAP_DianConnectionResp_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_DianConnectionResp_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DianConnectionResp = {
	"DianConnectionResp",
	"DianConnectionResp",
	&asn_OP_SEQUENCE,
	asn_DEF_DianConnectionResp_tags_1,
	sizeof(asn_DEF_DianConnectionResp_tags_1)
		/sizeof(asn_DEF_DianConnectionResp_tags_1[0]), /* 1 */
	asn_DEF_DianConnectionResp_tags_1,	/* Same as above */
	sizeof(asn_DEF_DianConnectionResp_tags_1)
		/sizeof(asn_DEF_DianConnectionResp_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DianConnectionResp_1,
	4,	/* Elements count */
	&asn_SPC_DianConnectionResp_specs_1	/* Additional specs */
};

