/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DianProtocol"
 * 	found in "dian.asn"
 * 	`asn1c -pdu=auto`
 */

#include "DianConnectionRequest.h"

static asn_TYPE_member_t asn_MBR_DianConnectionRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DianConnectionRequest, userIdentity),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_User_Identity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"userIdentity"
		},
};
static const ber_tlv_tag_t asn_DEF_DianConnectionRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DianConnectionRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 } /* userIdentity */
};
static asn_SEQUENCE_specifics_t asn_SPC_DianConnectionRequest_specs_1 = {
	sizeof(struct DianConnectionRequest),
	offsetof(struct DianConnectionRequest, _asn_ctx),
	asn_MAP_DianConnectionRequest_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DianConnectionRequest = {
	"DianConnectionRequest",
	"DianConnectionRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_DianConnectionRequest_tags_1,
	sizeof(asn_DEF_DianConnectionRequest_tags_1)
		/sizeof(asn_DEF_DianConnectionRequest_tags_1[0]), /* 1 */
	asn_DEF_DianConnectionRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_DianConnectionRequest_tags_1)
		/sizeof(asn_DEF_DianConnectionRequest_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DianConnectionRequest_1,
	1,	/* Elements count */
	&asn_SPC_DianConnectionRequest_specs_1	/* Additional specs */
};

