/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_DianConnectionRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_DianConnectionResp;
extern struct asn_TYPE_descriptor_s asn_DEF_DianSendMsg;
extern struct asn_TYPE_descriptor_s asn_DEF_DianMsgBroadcast;
extern struct asn_TYPE_descriptor_s asn_DEF_DianServerClosing;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module DianProtocol in dian.asn */
	&asn_DEF_DianConnectionRequest,	
	&asn_DEF_DianConnectionResp,	
	&asn_DEF_DianSendMsg,	
	&asn_DEF_DianMsgBroadcast,	
	&asn_DEF_DianServerClosing,	
	0
};

