/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DianProtocol"
 * 	found in "dian.asn"
 * 	`asn1c -pdu=auto`
 */

#include "Response-Type.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_Response_Type_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Response_Type_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_Response_Type_value2enum_1[] = {
	{ 0,	6,	"accept" },
	{ 1,	4,	"deny" },
	{ 2,	7,	"unknown" }
};
static const unsigned int asn_MAP_Response_Type_enum2value_1[] = {
	0,	/* accept(0) */
	1,	/* deny(1) */
	2	/* unknown(2) */
};
const asn_INTEGER_specifics_t asn_SPC_Response_Type_specs_1 = {
	asn_MAP_Response_Type_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_Response_Type_enum2value_1,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_Response_Type_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Response_Type = {
	"Response-Type",
	"Response-Type",
	&asn_OP_NativeEnumerated,
	asn_DEF_Response_Type_tags_1,
	sizeof(asn_DEF_Response_Type_tags_1)
		/sizeof(asn_DEF_Response_Type_tags_1[0]), /* 1 */
	asn_DEF_Response_Type_tags_1,	/* Same as above */
	sizeof(asn_DEF_Response_Type_tags_1)
		/sizeof(asn_DEF_Response_Type_tags_1[0]), /* 1 */
	{ &asn_OER_type_Response_Type_constr_1, &asn_PER_type_Response_Type_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_Response_Type_specs_1	/* Additional specs */
};

