/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DianProtocol"
 * 	found in "dian.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_Deny_Reason_H_
#define	_Deny_Reason_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Deny_Reason {
	Deny_Reason_identityrepeated	= 0,
	Deny_Reason_unknown	= 1
} e_Deny_Reason;

/* Deny-Reason */
typedef long	 Deny_Reason_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Deny_Reason_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Deny_Reason;
extern const asn_INTEGER_specifics_t asn_SPC_Deny_Reason_specs_1;
asn_struct_free_f Deny_Reason_free;
asn_struct_print_f Deny_Reason_print;
asn_constr_check_f Deny_Reason_constraint;
ber_type_decoder_f Deny_Reason_decode_ber;
der_type_encoder_f Deny_Reason_encode_der;
xer_type_decoder_f Deny_Reason_decode_xer;
xer_type_encoder_f Deny_Reason_encode_xer;
oer_type_decoder_f Deny_Reason_decode_oer;
oer_type_encoder_f Deny_Reason_encode_oer;
per_type_decoder_f Deny_Reason_decode_uper;
per_type_encoder_f Deny_Reason_encode_uper;
per_type_decoder_f Deny_Reason_decode_aper;
per_type_encoder_f Deny_Reason_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Deny_Reason_H_ */
#include <asn_internal.h>
