/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DianProtocol"
 * 	found in "dian.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_DianConnectionResp_H_
#define	_DianConnectionResp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "User-Identity.h"
#include "Response-Type.h"
#include "Deny-Reason.h"
#include "Message.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DianConnectionResp */
typedef struct DianConnectionResp {
	User_Identity_t	 userIdentity;
	Response_Type_t	 respType;
	Deny_Reason_t	*denyReason;	/* OPTIONAL */
	Message_t	*helloMsg;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DianConnectionResp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DianConnectionResp;

#ifdef __cplusplus
}
#endif

#endif	/* _DianConnectionResp_H_ */
#include <asn_internal.h>
