/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DianProtocol"
 * 	found in "dian.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_DianMsgBroadcast_H_
#define	_DianMsgBroadcast_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Message.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DianMsgBroadcast */
typedef struct DianMsgBroadcast {
	Message_t	 msg;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DianMsgBroadcast_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DianMsgBroadcast;

#ifdef __cplusplus
}
#endif

#endif	/* _DianMsgBroadcast_H_ */
#include <asn_internal.h>
