/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DianProtocol"
 * 	found in "dian.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_Message_H_
#define	_Message_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Message */
typedef PrintableString_t	 Message_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Message_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Message;
asn_struct_free_f Message_free;
asn_struct_print_f Message_print;
asn_constr_check_f Message_constraint;
ber_type_decoder_f Message_decode_ber;
der_type_encoder_f Message_encode_der;
xer_type_decoder_f Message_decode_xer;
xer_type_encoder_f Message_encode_xer;
oer_type_decoder_f Message_decode_oer;
oer_type_encoder_f Message_encode_oer;
per_type_decoder_f Message_decode_uper;
per_type_encoder_f Message_encode_uper;
per_type_decoder_f Message_decode_aper;
per_type_encoder_f Message_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Message_H_ */
#include <asn_internal.h>
