/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DianProtocol"
 * 	found in "dian.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_Response_Type_H_
#define	_Response_Type_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Response_Type {
	Response_Type_accept	= 0,
	Response_Type_deny	= 1,
	Response_Type_unknown	= 2
} e_Response_Type;

/* Response-Type */
typedef long	 Response_Type_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Response_Type_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Response_Type;
extern const asn_INTEGER_specifics_t asn_SPC_Response_Type_specs_1;
asn_struct_free_f Response_Type_free;
asn_struct_print_f Response_Type_print;
asn_constr_check_f Response_Type_constraint;
ber_type_decoder_f Response_Type_decode_ber;
der_type_encoder_f Response_Type_encode_der;
xer_type_decoder_f Response_Type_decode_xer;
xer_type_encoder_f Response_Type_encode_xer;
oer_type_decoder_f Response_Type_decode_oer;
oer_type_encoder_f Response_Type_encode_oer;
per_type_decoder_f Response_Type_decode_uper;
per_type_encoder_f Response_Type_encode_uper;
per_type_decoder_f Response_Type_decode_aper;
per_type_encoder_f Response_Type_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Response_Type_H_ */
#include <asn_internal.h>
