/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DianProtocol"
 * 	found in "dian.asn"
 */

#ifndef	_DianPDU_H_
#define	_DianPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DianConnectionRequest.h"
#include "DianConnectionResp.h"
#include "DianSendMsg.h"
#include "DianMsgBroadcast.h"
#include "DianServerClosing.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DianPDU_PR {
	DianPDU_PR_NOTHING,	/* No components present */
	DianPDU_PR_dianConnectionRequest,
	DianPDU_PR_dianConnectionResp,
	DianPDU_PR_dianSendMsg,
	DianPDU_PR_dianMsgBroadcast,
	DianPDU_PR_dianServerclosing
} DianPDU_PR;

/* DianPDU */
typedef struct DianPDU {
	DianPDU_PR present;
	union DianPDU_u {
		DianConnectionRequest_t	 dianConnectionRequest;
		DianConnectionResp_t	 dianConnectionResp;
		DianSendMsg_t	 dianSendMsg;
		DianMsgBroadcast_t	 dianMsgBroadcast;
		DianServerClosing_t	 dianServerclosing;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DianPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DianPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _DianPDU_H_ */
#include <asn_internal.h>
