/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DianProtocol"
 * 	found in "dian.asn"
 */

#ifndef	_DianServerClosing_H_
#define	_DianServerClosing_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Message.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DianServerClosing */
typedef struct DianServerClosing {
	Message_t	 exitMsg;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DianServerClosing_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DianServerClosing;
extern asn_SEQUENCE_specifics_t asn_SPC_DianServerClosing_specs_1;
extern asn_TYPE_member_t asn_MBR_DianServerClosing_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _DianServerClosing_H_ */
#include <asn_internal.h>
