/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DianProtocol"
 * 	found in "dian.asn"
 */

#ifndef	_User_Identity_H_
#define	_User_Identity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* User-Identity */
typedef long	 User_Identity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_User_Identity;
asn_struct_free_f User_Identity_free;
asn_struct_print_f User_Identity_print;
asn_constr_check_f User_Identity_constraint;
ber_type_decoder_f User_Identity_decode_ber;
der_type_encoder_f User_Identity_encode_der;
xer_type_decoder_f User_Identity_decode_xer;
xer_type_encoder_f User_Identity_encode_xer;
oer_type_decoder_f User_Identity_decode_oer;
oer_type_encoder_f User_Identity_encode_oer;
per_type_decoder_f User_Identity_decode_uper;
per_type_encoder_f User_Identity_encode_uper;
per_type_decoder_f User_Identity_decode_aper;
per_type_encoder_f User_Identity_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _User_Identity_H_ */
#include <asn_internal.h>
