/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DianProtocol"
 * 	found in "dian.asn"
 */

#include "DianPDU.h"

static asn_oer_constraints_t asn_OER_type_DianPDU_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_DianPDU_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  4 }	/* (0..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_DianPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DianPDU, choice.dianConnectionRequest),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DianConnectionRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dianConnectionRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DianPDU, choice.dianConnectionResp),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DianConnectionResp,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dianConnectionResp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DianPDU, choice.dianSendMsg),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DianSendMsg,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dianSendMsg"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DianPDU, choice.dianMsgBroadcast),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DianMsgBroadcast,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dianMsgBroadcast"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DianPDU, choice.dianServerclosing),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DianServerClosing,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dianServerclosing"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_DianPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dianConnectionRequest */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dianConnectionResp */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* dianSendMsg */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* dianMsgBroadcast */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* dianServerclosing */
};
static asn_CHOICE_specifics_t asn_SPC_DianPDU_specs_1 = {
	sizeof(struct DianPDU),
	offsetof(struct DianPDU, _asn_ctx),
	offsetof(struct DianPDU, present),
	sizeof(((struct DianPDU *)0)->present),
	asn_MAP_DianPDU_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_DianPDU = {
	"DianPDU",
	"DianPDU",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_DianPDU_constr_1, &asn_PER_type_DianPDU_constr_1, CHOICE_constraint },
	asn_MBR_DianPDU_1,
	5,	/* Elements count */
	&asn_SPC_DianPDU_specs_1	/* Additional specs */
};

